### ISSUE TITLE
Reactivating runes after server restart

### ISSUE THREAD

**Issue by Vectarrio** [Chekote/Blink#17]
Is there a way to save their activation status, so they won't need to be reactivated when server starts again? And maybe a config line for that, so if it appears unbalanced, then turn that reactivation off

**Comment by Chekote** [comment]
The runes should not need to be reactivated after a server restart. They are saved to blink_runes.json when the server shuts down, and are reloaded automatically when it restarts.

Are you shutting down the server cleanly? If the server crashes, or if you force it to shut down without letting it do so gracefully, then the runes will not be saved.

The blink_runes.json file should be in the `saves/WORLD_NAME/` folder.

If you are shutting it down property but it's still not saving, can you send me more info on the environment you're running it on? e.g. OS, Java Version, Minecraft Version, Force Version, Runic Blink Version.

**Comment by Chekote** [comment]
Thank you for reporting the issue. I was finally able to re-create it and it was fixed in version 1.5.0.
