### ISSUE TITLE
NullPointerException if teleporting across dimensions

### ISSUE THREAD

**Issue by IngmarBitter** [Chekote/Blink#2]
I'm using Blink + [simpledimensions](https://minecraft.curseforge.com/projects/simple-dimensions)
Most conveniently this is setup through technic launcher and its mod pack [atlantica-next](https://www.technicpack.net/modpack/atlantica-next.1060323) - just add blink to the mods directory.

In game I made the 5x5 rune patterns and happily teleported. The rune patterns were in the same dimension.  When adding a new dimension with _/simpledimensions create_  and subsequently going there with _/tpd 30000_ and then finally making another rune pattern there  - I was hoping I could teleport between dimensions, but trying to blink Minecraft crashed with NullPointerException, see stacktrace from the the log below. Please fix.

> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_144]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chb.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.world.Teleporter.func_180620_b(SourceFile:128) ~[ana.class:?]
> 	at net.minecraft.world.Teleporter.func_180266_a(SourceFile:65) ~[ana.class:?]
> 	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:707) ~[pj.class:?]
> 	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:617) ~[pj.class:?]
> 	at net.minecraft.server.management.PlayerList.func_187242_a(PlayerList.java:604) ~[pj.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:695) ~[oo.class:?]
> 	at com.monkeyinabucket.forge.blink.rune.BlinkRune.activate(BlinkRune.java:142) ~[BlinkRune.class:?]
> 	at com.monkeyinabucket.forge.blink.block.RuneCore.activate(RuneCore.java:148) ~[RuneCore.class:?]
> 	at com.monkeyinabucket.forge.blink.block.RuneCore.func_180639_a(RuneCore.java:64) ~[RuneCore.class:?]
> 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[op.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:729) ~[oy.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[lz.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[lz.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_144]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_144]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more

**Comment by Chekote** [comment]
Thanks so much for reporting this! I'll look into it right away ^_^

**Comment by Chekote** [comment]
Which version of my Mod were you using when this happened?

**Comment by Chekote** [comment]
I've not been able to recreate this with teleporting between the overworld and the nether. I'll go grab a copy of that modpack and see if I can re-create it with that. If you could tell me what version you have the issue with, it'd help shortcut the process. Thanks!

**Comment by IngmarBitter** [comment]
It was with Tuesday's 1.12 version.
I'll try it again with teleporting to the nether, see if that works/fails.

**Comment by IngmarBitter** [comment]
I just tried _Chekote-blink-1.12-1.0.0.jar_ and [Atlantica-Next 1.35 modpack](https://www.technicpack.net/modpack/atlantica-next.1060323/about) and they now work fine together! Can teleport to nether and to a new simple dimension!  It seems this can be set to not reproducible? Or should I go back to the older version of the modpack to reproduce there (not needed I think) ?

**Comment by Chekote** [comment]
I managed to reproduce the bug if I create two runes in the overworld and then a third in the simpledimensions world. So it's definitely reproducable.

I did another test where I created one rune in the overworld, then one in the nether, then a third in the simpledimensions world, and the bug did not manifest itself there.

I'll keep investigating.

**Comment by Chekote** [comment]
Some really weird stuff going on with either forge or the simple dimensions mod. I re-loaded a world where I had re-created the null pointer exception and the game had generated a Nether portal embedded in the destination rune... I wasn't even traveling from the Nether. So weird... o.O

**Comment by Chekote** [comment]
I think this might be a problem with something that simple dimensions is doing. The null pointer exception is occurring after I call `net.minecraft.entity.player.EntityPlayerMP.changeDimension()`, which I'm only passing the dimension id to. Between that point and the point at which the Exception is thrown, the code path is completely within Minecraft's internal code.

There's also this issue on the simple dimensions repo that is still open and sounds very similar to the problem were seeing here: https://github.com/lumien231/Simple-Dimensions/issues/6

**Comment by IngmarBitter** [comment]
good detective work!
Let's hope simple dimensions developers are as responsive as you :-)

**Comment by Chekote** [comment]
I want to do further investigation with different Forge versions. If those still have the same behavior, I'm going to assume this is a Simple Dimensions bug and close the issue here.

Thanks so much for helping me look into this.
