### ISSUE TITLE
Can't break runes in Creative Mode

### ISSUE THREAD

**Issue by CplPibald** [Chekote/Blink#27]
When a creative player tries to break any block that is part of a rune, the entire rune goes up in flames, and it causes a client/server desync.  The block appears to be gone, but trying to interact with the block (or just logging out and back in again) shows the whole rune is still intact.

**Comment by Chekote** [comment]
Thanks so much for the bug report!

What version of Minecraft and the mod are you experiencing this on?

This seems to be already recorded under issue #5, so I'll close this as a dupe. If you feel this is not the same bug, please feel free to comment and re-open the issue.
